telegram:
  bot:
    token: 7541485616:AAEdIisgoadQ7Ve8SxF03L5zgS79fZnwFYI
    username: https://t.me/SmartPhoneBrendBot

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SmartPhoneBrendBot
    username: root
    password: 1995hakimov19
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  sql:
    init:
      mode: always

server:
  port: 8082  # Yangi port raqamini kiritamiz

